[package]
name = "sasm"
version = "0.1.0"
authors = ["Alexander Theißen <alex@theissen.io>"]

[dependencies]
yew = { git = "https://github.com/DenisKolodin/yew.git" }
stdweb = "0.4.7"
serde = "1.0.70"
serde_derive = "1.0.70"
